const itemLevel = ["hero", "legend", "relic", "ancient", "esther"];
const ItemCount = [
  { value: "0", label: "0" },
  { value: "1", label: "1" },
  { value: "2", label: "2" },
  { value: "3", label: "3" },
  { value: "4", label: "4" },
  { value: "5", label: "5" },
  { value: "6", label: "6" },
];
const ItemCount2 = [
  { value: "0", label: "0" },
  { value: "1", label: "1" },
  { value: "2", label: "2" },
  { value: "3", label: "3" },
];
const stoneCount = [
  { value: "0", label: "0" },
  { value: "1", label: "1" },
  { value: "2", label: "2" },
  { value: "3", label: "3" },
  { value: "4", label: "4" },
  { value: "5", label: "5" },
  { value: "6", label: "6" },
  { value: "7", label: "7" },
  { value: "8", label: "8" },
  { value: "9", label: "9" },
  { value: "10", label: "10" },
];
const engCount = [
  { value: "0", label: "0" },
  { value: "3", label: "3" },
  { value: "6", label: "6" },
  { value: "9", label: "9" },
  { value: "12", label: "12" },
];
const engrainjgObj = [
  { value: "원한", label: "원한" },
  { value: "저주받은 인형", label: "저주받은 인형" },
  { value: "예리한 둔기", label: "예리한 둔기" },
  { value: "각성", label: "각성" },
  { value: "바리게이트", label: "바리게이트" },
  { value: "타격의 대가", label: "타격의 대가" },
  { value: "정밀 단도", label: "정밀 단도" },
  { value: "타격의 대가", label: "타격의 대가" },
  { value: "중갑 착용", label: "중갑 착용" },
  { value: "질량 증가", label: "질량 증가" },
  { value: "아드레날린", label: "아드레날린" },
  { value: "강령술", label: "강령술" },
  { value: "강화 방패", label: "강화 방패" },
  { value: "결투의 대가", label: "결투의 대가" },
  { value: "구슬동자", label: "구슬동자" },
  { value: "굳은 의지", label: "굳은 의지" },
  { value: "급소 타격", label: "급소 타격" },
  { value: "기습의 대가", label: "기습의 대가" },
  { value: "긴급구조", label: "긴급구조" },
  { value: "달인의 저력", label: "달인의 저력" },
  { value: "돌격대장", label: "돌격대장" },
  { value: "마나의 흐름", label: "마나의 흐름" },
  { value: "마나 효율 증가", label: "마나 효율 증가" },
  { value: "번개의 분노", label: "번개의 분노" },
  { value: "부러진 뼈", label: "부러진 뼈" },
  { value: "불굴", label: "불굴" },
  { value: "선수필승", label: "선수필승" },
  { value: "속전속결", label: "속전속결" },
  { value: "슈퍼 차지", label: "슈퍼 차지" },
  { value: "승부사", label: "승부사" },
  { value: "시선 집중", label: "시선 집중" },
  { value: "실드 관통", label: "실드 관통" },
  { value: "안정된 상태", label: "안정된 상태" },
  { value: "약자 무시", label: "약자 무시" },
  { value: "여신의 가호", label: "여신의 가호" },
  { value: "에테르 포식자", label: "에테르 포식자" },
  { value: "위기 모면", label: "위기 모면" },
  { value: "전문의", label: "전문의" },
  { value: "정기 흡수", label: "정기 흡수" },
  { value: "정밀 단도", label: "정밀 단도" },
  { value: "질량 증가", label: "질량 증가" },
  { value: "최대 마나 증가", label: "최대 마나 증가" },
  { value: "추진력", label: "추진력" },
  { value: "타격의 대가", label: "타격의 대가" },
  { value: "탈출의 명수", label: "탈출의 명수" },
  { value: "폭발물 전문가", label: "폭발물 전문가" },
  { value: "버서커 : 광기", label: "버서커 : 광기" },
  { value: "버서커 : 광전사의 비기", label: "버서커 : 광전사의 비기" },
  { value: "워로드 : 전투 태세", label: "워로드 : 전투 태세" },
  { value: "워로드 : 고독한 기사", label: "워로드 : 고독한 기사" },
  { value: "디스트로이어 : 분노의 망치", label: "디스트로이어 : 분노의 망치" },
  { value: "디스트로이어 : 중력 수련", label: "디스트로이어 : 중력 수련" },
  { value: "홀리나이트 : 심판자", label: "홀리나이트 : 심판자" },
  { value: "홀리나이트 : 축복의 오라", label: "홀리나이트 : 축복의 오라" },
  { value: "배틀마스터 : 오의강화", label: "배틀마스터 : 오의강화" },
  { value: "배틀마스터 : 초심", label: "배틀마스터 : 초심" },
  { value: "인파이터 : 극의 : 체술", label: "인파이터 : 극의 : 체술" },
  { value: "인파이터 : 충격 단련", label: "인파이터 : 충격 단련" },
  { value: "기공사 : 세맥타통", label: "기공사 : 세맥타통" },
  { value: "기공사 : 역천지체", label: "기공사 : 역천지체" },
  { value: "창술사 : 절정", label: "창술사 : 절정" },
  { value: "창술사 : 절제", label: "창술사 : 절제" },
  { value: "데빌헌터 : 강화 무기", label: "데빌헌터 : 강화 무기" },
  { value: "데빌헌터 : 핸드거너", label: "데빌헌터 : 핸드거너" },
  { value: "블래스터 : 화력 강화", label: "블래스터 : 화력 강화" },
  { value: "블래스터 : 포격 강화", label: "블래스터 : 포격 강화" },
  { value: "호크아이 : 두 번째 동료", label: "호크아이 : 두 번째 동료" },
  { value: "호크아이 : 죽음의 습격", label: "호크아이 : 죽음의 습격" },
  {
    value: "스카우터 : 아르데타인의 기술",
    label: "스카우터 : 아르데타인의 기술",
  },
  { value: "스카우터 : 진화의 유산", label: "스카우터 : 진화의 유산" },
  { value: "바드 : 진실된 용맹", label: "바드 : 진실된 용맹" },
  { value: "바드 : 절실한 구원", label: "바드 : 절실한 구원" },
  { value: "서머너 : 상급 소환사", label: "서머너 : 상급 소환사" },
  { value: "서머너 : 넘치는 교감", label: "서머너 : 넘치는 교감" },
  { value: "아르나카 : 황후의 은총", label: "아르나카 : 황후의 은총" },
  { value: "아르나카 : 황제의 칙령", label: "아르나카 : 황제의 칙령" },
  { value: "소서리스 : 점화", label: "소서리스 : 점화" },
  { value: "소서리스 : 환류", label: "소서리스 : 환류" },
  { value: "블레이드 : 잔재된 기운", label: "블레이드 : 잔재된 기운" },
  { value: "블레이드 : 버스트", label: "블레이드 : 버스트" },
  { value: "데모닉 : 멈출 수 없는 충동", label: "데모닉 : 멈출 수 없는 충동" },
  { value: "데모닉 : 완벽한 억제", label: "데모닉 : 완벽한 억제" },
  { value: "리퍼 : 갈증", label: "리퍼 : 갈증" },
  { value: "리퍼 : 달의 소리", label: "리퍼 : 달의 소리" },
  { value: "건슬링어 : 사냥의 시간", label: "건슬링어 : 사냥의 시간" },
  { value: "건슬링어 : 피스메이커", label: "건슬링어 : 피스메이커" },
  { value: "스트라이커 : 일격필살", label: "스트라이커 : 일격필살" },
  { value: "스트라이커 : 오의난무", label: "스트라이커 : 오의난무" },
];
const maItem = [
  { value: "공격력 감소", label: "공격력 감소" },
  { value: "이동속도 감소", label: "이동속도 감소" },
  { value: "공격속도 감소", label: "공격속도 감소" },
  { value: "방어력 감소", label: "방어력 감소" },
];
const necklaceName = [
  { value: "0", label: "공허한 운명의 목걸이" },
  { value: "1", label: "참혹한 파멸의 목걸이" },
  { value: "2", label: "거룩한 수호자의 목걸이" }, //고대
  { value: "3", label: "타락한 시간의 목걸이" },
  { value: "4", label: "울부짖는 혼돈의 목걸이" },
  { value: "5", label: "찬란한 구도자의 목걸이" }, //유물
];
const defaultList = () => {
  return [
    {
      name: "목걸이",
      level: itemLevel,
      selectItem: ItemCount,
      engrainjg: engrainjgObj,
      maItem: maItem,
      ItemCount2: ItemCount2,
      itemName: necklaceName,
    },
    {
      name: "귀걸이",
      level: itemLevel,
      selectItem: ItemCount,
      engrainjg: engrainjgObj,
      maItem: maItem,
      ItemCount2: ItemCount2,
    },
    {
      name: "귀걸이",
      level: itemLevel,
      selectItem: ItemCount,
      engrainjg: engrainjgObj,
      maItem: maItem,
      ItemCount2: ItemCount2,
    },
    {
      name: "반지",
      level: itemLevel,
      selectItem: ItemCount,
      engrainjg: engrainjgObj,
      maItem: maItem,
      ItemCount2: ItemCount2,
    },
    {
      name: "반지",
      level: itemLevel,
      selectItem: ItemCount,
      engrainjg: engrainjgObj,
      maItem: maItem,
      ItemCount2: ItemCount2,
    },
    {
      name: "돌",
      level: itemLevel,
      selectItem: stoneCount,
      engrainjg: engrainjgObj,
      maItem: maItem,
      ItemCount2: ItemCount2,
    },
    {
      name: "각인",
      selectItem: engCount,
      engrainjg: engrainjgObj,
    },
    {
      name: "각인",
      selectItem: engCount,
      engrainjg: engrainjgObj,
    },
  ];
};
export default defaultList();
